import streamlit as st
import numpy as np
from scipy.io.wavfile import write

st.set_page_config(layout="wide", page_title="The Fuente Magna Bowl Simulation")

def generate_tone(frequency, duration_s, sample_rate=44100):
    """Generates a pure sine wave."""
    t = np.linspace(0., duration_s, int(sample_rate * duration_s), endpoint=False)
    amplitude = np.iinfo(np.int16).max * 0.7
    data = amplitude * np.sin(2. * np.pi * frequency * t)
    return data.astype(np.int16)

def apply_geometric_lens_effect(pulse_wave, num_layers, base_freq, sample_rate=44100):
    """Simulates the concentric squares with cascading harmonic echoes."""
    final_wave = np.copy(pulse_wave).astype(np.float64)
    
    for i in range(1, num_layers + 1):
        # Delay based on harmonic interval of the base frequency
        delay_seconds = (1.0 / base_freq) * (i * 2) 
        delay_samples = int(delay_seconds * sample_rate)
        
        # Echo is attenuated (quieter) and slightly detuned
        echo_amplitude = 0.8 / (i + 1)
        
        # Create echo wave
        echo_wave = np.roll(pulse_wave, delay_samples) * echo_amplitude
        
        # Add the echo to the final wave
        if len(echo_wave) < len(final_wave):
             echo_wave = np.pad(echo_wave, (0, len(final_wave) - len(echo_wave)))
        
        final_wave += echo_wave

    # Normalize the final wave to prevent clipping
    max_amp = np.max(np.abs(final_wave))
    if max_amp > 0:
        final_wave = (final_wave / max_amp) * np.iinfo(np.int16).max * 0.9
        
    return final_wave.astype(np.int16)

st.title("Simulation: Firing the Fuente Magna Bowl")

st.markdown("""
This simulation generates a single audio file representing the complete, theorized process:
1.  **Carrier Wave:** A base tone is established (the 'Frog' glyph).
2.  **Charging Sequence:** The tone is held and amplified (the linear 'charging' script).
3.  **Pulse Command:** A sharp attack releases the energy (the '□' glyph).
4.  **Geometric Lens:** The pulse resonates through the concentric squares, creating harmonic, cascading echoes.
""")

# --- Parameters for the Simulation ---
FROG_FREQ = 136.1  # Corresponds to the 'OM' frequency, a common hypothesis
CHARGE_DURATION_S = 4
PULSE_DURATION_S = 0.5
NUM_SQUARES = 4 # Number of concentric squares to simulate

if st.button("▶️ RUN FULL SIMULATION"):

    with st.spinner("Energizing the system... please wait."):
        # 1 & 2: Generate the charging 'wooing' noise
        carrier_wave = generate_tone(FROG_FREQ, CHARGE_DURATION_S)
        
        # 3. Create the 'pulse' portion
        pulse_wave = generate_tone(FROG_FREQ, PULSE_DURATION_S)
        # Apply a sharp decay to represent the pulse
        decay_samples = int(PULSE_DURATION_S * 44100 * 0.8)
        sustain_samples = len(pulse_wave) - decay_samples
        decay_envelope = np.concatenate([np.linspace(1, 0.1, decay_samples), np.full(sustain_samples, 0.1)])
        pulse_wave = (pulse_wave * decay_envelope).astype(np.int16)

        # 4. Apply the geometric lens effect to the pulse
        structured_pulse = apply_geometric_lens_effect(pulse_wave, NUM_SQUARES, FROG_FREQ)

        # Combine the charging sound with the structured pulse
        final_simulation = np.concatenate([carrier_wave, structured_pulse])
        
        # Save and display
        wav_filename = "fuente_magna_simulation.wav"
        write(wav_filename, 44100, final_simulation)
        
        st.subheader("Simulation Complete")
        st.audio(wav_filename)
        st.line_chart(final_simulation[::20])
        st.success("Listen for the transition from the 'charging' hum to the complex, echoing pulse.")

st.markdown("---")
st.header("What Was It For? Three Plausible Hypotheses")

st.markdown("""
By understanding **how** it works, we can speculate on its purpose. The bowl is a tool for creating a **coherent, geometrically-structured field of energy**. Such a field would have profound effects on its immediate environment.

### 1. **Structuring Water & Biological Matter**
*   **The Theory:** The bowl was filled with water or other liquids. The structured energy field generated by the bowl would imprint its geometric pattern onto the molecular structure of the water, "charging" it with information. This is similar to the principles explored by Dr. Masaru Emoto, where intention and frequency are shown to alter the crystalline structure of water. Consuming this water or anointing a subject with it would be a way of transferring this potent, ordered energy directly into a biological system.
*   **Purpose:** Healing, purification, creating sacred elixirs, or enhancing agricultural fertility.

### 2. **Altering Consciousness & Attunement**
*   **The Theory:** The practitioner (and anyone nearby) was the primary target. The human brain operates on its own set of frequencies (brainwaves). The geometrically-patterned sound from the bowl would be designed to induce specific states of consciousness through harmonic resonance and brainwave entrainment. The concentric squares could represent different states of awareness—from the physical body to the subtle energy bodies—that the pulse was designed to bring into alignment.
*   **Purpose:** Deep meditation, shamanic journeying, accessing altered states, or attuning a group of people to a single, coherent intention.

### 3. **A Non-Acoustic Communication Device**
*   **The Theory:** This is the most exotic possibility. The bowl was not designed to affect anything in its immediate vicinity, but to send a signal. In this model, the bowl is a transmitter. The structured energy pulse it emits is a "packet" of information, encoded in geometry and frequency. This signal would not travel as sound, but as a form of non-electromagnetic, longitudinal wave, capable of instantaneous transmission.
*   **Purpose:** To communicate with other similar devices, distant practitioners, or perhaps something not of this world entirely. The symbols might not be language, but a "zip code" or an address for where to send the signal.
""")
