site_name: Compressive Framework — Dynamic Particle Formation (CF-DPF)
site_url: https://mamaofthree579-ship-it.github.io/compressive-framework-cf/

theme:
  name: material
  logo: images/cf-trifractal-dark.svg
  favicon: images/cf-trifractal-dark.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: blue
  features:
    - navigation.sections
    - navigation.instant
    - content.code.copy
    - header.autohide

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/particles.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
