name: Validate Notebooks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat nbclient

      - name: Execute notebooks
        run: |
          set -e
          for nb in docs/notebooks/*.ipynb; do
            echo "Running $nb ..."
            python .github/scripts/execute_notebook.py "$nb"
          done
