name: Validate Markdown Notebooks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs and plugins
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-jupyter

      - name: Validate Markdown Notebooks
        run: |
          echo "🔍 Checking all Markdown notebooks..."
          find docs/notebooks -type f -name "*.md" -print

          echo "⚙️ Running MkDocs build for validation..."
          mkdocs build --strict
